# Generated by Django 4.1.4 on 2022-12-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nome', models.CharField(max_length=50, verbose_name='Produto')),
                ('pro_status', models.CharField(choices=[('OK', 'Disponível'), ('-', 'Recebido')], max_length=3, verbose_name='Status')),
                ('pro_doador', models.CharField(max_length=100, verbose_name='Doador')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('tel_dono', models.CharField(max_length=100, verbose_name='Dono')),
            ],
        ),
    ]
